CREATE DATABASE IF NOT EXISTS QUIZ;

USE QUIZ;

CREATE TABLE IF NOT EXISTS USERS(
    USERS_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    EMAIL VARCHAR(75) NOT NULL,
    PASSWORD VARCHAR(75) NOT NULL,
    IS_ACTIVE BIT NOT NULL,
    PRIMARY KEY(USERS_ID)
);

CREATE TABLE IF NOT EXISTS ADMINISTRATOR(
    ADMIN_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    EMAIL VARCHAR(75) NOT NULL,
    PASSWORD VARCHAR(75) NOT NULL,
    PRIMARY KEY(ADMIN_ID)
);

CREATE TABLE IF NOT EXISTS TEST(
    TEST_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    ADMIN_ID INT UNSIGNED NOT NULL,
    HAS_IMAGE BIT NOT NULL,
    IMAGE_NAME VARCHAR(25) NOT NULL,
    FOREIGN KEY(ADMIN_ID) REFERENCES ADMINISTRATOR(ADMIN_ID) ON DELETE CASCADE,
    PRIMARY KEY(TEST_ID)
);

CREATE TABLE IF NOT EXISTS ANSWERS(
    ANSWERS_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    IS_TRUE_FALSE BIT NOT NULL,
    NUM_ANSWERS INT UNSIGNED,
    ANSWER_ONE VARCHAR(25),
    ANSWER_TWO VARCHAR(25),
    ANSWER_THREE VARCHAR(25),
    ANSWER_FOUR VARCHAR(25),
    ANSWER_FIVE VARCHAR(25),
    ANSWER_SIX VARCHAR(25),
    CORRECT_ANSWER INT UNSIGNED NOT NULL,
    PRIMARY KEY(ANSWERS_ID)
);

CREATE TABLE IF NOT EXISTS QUESTIONS(
    QUESTION_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    TEXT VARCHAR(250) NOT NULL,
    CATEGORY VARCHAR(75) NOT NULL,
    HAS_IMAGE BIT NOT NULL,
    IMAGE_NAME VARCHAR(25) NOT NULL,
    ANSWERS_ID INT UNSIGNED NOT NULL,
    FOREIGN KEY(ANSWERS_ID) REFERENCES ANSWERS(ANSWERS_ID) ON DELETE CASCADE,
    PRIMARY KEY(QUESTION_ID)

);

CREATE TABLE IF NOT EXISTS TEST_QUESTIONS(
    TEST_ID INT UNSIGNED NOT NULL,
    QUESTION_ID INT UNSIGNED NOT NULL,
    FOREIGN KEY(TEST_ID) REFERENCES TEST(TEST_ID) ON DELETE CASCADE,
    FOREIGN KEY(QUESTION_ID) REFERENCES QUESTIONS(QUESTION_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ALLOWED_USERS(
    USERS_ID INT UNSIGNED NOT NULL,
    TEST_ID INT UNSIGNED NOT NULL,
    FOREIGN KEY(USERS_ID) REFERENCES USERS(USERS_ID) ON DELETE CASCADE,
    FOREIGN KEY(TEST_ID) REFERENCES TEST(TEST_ID) ON DELETE CASCADE    
);

CREATE TABLE IF NOT EXISTS RESULTS(
    RESULTS_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    QUESTION_ID INT UNSIGNED NOT NULL,
    SELECTED_ANSWER INT UNSIGNED NOT NULL,
    PRIMARY KEY(RESULTS_ID),
    FOREIGN KEY(QUESTION_ID) REFERENCES QUESTIONS(QUESTION_ID) ON DELETE CASCADE
);

/* http://www.mysqltutorial.org/mysql-datetime/ */
CREATE TABLE IF NOT EXISTS TESTS_TAKEN(
    USERS_ID INT UNSIGNED NOT NULL,
    TEST_ID INT UNSIGNED NOT NULL,
    RESULTS_ID INT UNSIGNED NOT NULL,
    TEST_DT DATETIME NOT NULL,
    FOREIGN KEY(USERS_ID) REFERENCES USERS(USERS_ID) ON DELETE CASCADE,
    FOREIGN KEY(TEST_ID) REFERENCES TEST(TEST_ID) ON DELETE CASCADE,
    FOREIGN KEY(RESULTS_ID) REFERENCES RESULTS(RESULTS_ID) ON DELETE CASCADE
);