CREATE DATABASE IF NOT EXISTS QUIZ;

USE QUIZ;

CREATE TABLE IF NOT EXISTS USER(
    USER_ID INT AUTO_INCREMENT,
    EMAIL VARCHAR(75) NOT NULL,
    PASSWORD VARCHAR(75) NOT NULL,
    IS_ACTIVE BIT NOT NULL,
    PRIMARY KEY(USER_ID)
);

CREATE TABLE IF NOT EXISTS ADMINISTRATOR(
    ADMIN_ID INT AUTO_INCREMENT,
    EMAIL VARCHAR(75) NOT NULL,
    PASSWORD VARCHAR(75) NOT NULL,
    PRIMARY KEY(ADMIN_ID)
);

