USE QUIZ;

INSERT INTO USERS (EMAIL, PASSWORD, IS_ACTIVE)
VALUES ('active@gmail.com', 'csi2019', 1);

INSERT INTO USERS (EMAIL, PASSWORD, IS_ACTIVE)
VALUES ('inactive@gmail.com', 'csi2019', 0);

INSERT INTO ADMINISTRATOR (EMAIL, PASSWORD)
VALUES ('admin@gmail.com', 'csi2019');