USE QUIZ;

DELIMITER // 

CREATE PROCEDURE UPDATE_MC_QUESTION(BOOK_CODE_ARG CHAR(4), PAPERBACK_ARG CHAR(1), PRICE_ARG DECIMAL(4,2))
BEGIN
	UPDATE BOOK
    SET PRICE = PRICE_ARG 
    WHERE (BOOK_CODE = BOOK_CODE_ARG AND PAPERBACK = PAPERBACK_ARG);
END //

DELIMITER ;